import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Providers from "./Providers";
import Navbar from "@/components/Navbar/Navbar";
import LayoutWrapper from "./LayoutWrapper"; // Import the LayoutWrapper to manage Navbar visibility

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Providers>
          <div className="flex text-foreground">
            {/* <Navbar /> */}
            <LayoutWrapper>
            <main className="min-h-dvh overflow-y-auto">
              <div className="mx-auto w-full  p-6">
                {children}
              </div>
            </main>
            </LayoutWrapper>
          </div>
          {/* <LayoutWrapper>
            <main>
              {children}
            </main>
          </LayoutWrapper> */}
        </Providers>
      </body>
    </html>
  );
}
