export const ReportResult =[ {  //for result and delete
    id: "",
    specimens_id: "",
    doctor_id: "",
    patient_id: "",
    pharm_verify: false,
    medtech_verify: false,
    note_id: "",
    rule_id: "",
    index_rule: 0,
    more_information: [],
    pharmacist_id: "",
    medical_technician_id: "",
    status: "",
    request_date: "",
    report_date: "",
    created_at: "",
    updated_at: ""
}]
export const ReportResultOne = {  //for result and delete
    id: "",
    specimens_id: "",
    specimens_name: "",
    specimens_expire_date: "",
    doctor_id: "",
    doctor_fullname: "",
    doctor_license: "",
    patient_id: "",
    Eng_name: "",
    Thai_name: "",
    DOB: "",
    age: 0,
    gender: "",
    ethnicity: "",
    pharm_verify: false,
    medtech_verify: false,
    note_id: "",
    note_method: "",
    rule_id: "",
    rule_name: "",
    rule_location: "",
    rule_result_location: "",
    rule_phenotype: "",
    rule_predicted_genotype: "",
    rule_predicted_phenotype: "",
    rule_recommendation: "",
    index_rule: 0,
    more_information: [],
    pharmacist_id: "",
    fullname_pharmacist: "",
    pharmacist_license: "",
    medical_technician_id: "",
    fullname_medtech: "",
    medical_technician_license: "",
    status: "",
    request_date: "",
    report_date: "",
    created_at: "",
    updated_at: ""

}

export const ReportModel = {  //for create body
    specimens_id: "",
    patient_id: "",
    status: "",
}

export const ReportUpdate = {  //for update
    doctor_id: "",
    pharm_verify: false,
    medtech_verify: false,
    note_id: "",
    rule_id: [],
    index_rule: 0,
    more_information: [],
    pharmacist_id: "",
    medical_technician_id: "",
    request_date: "",
    report_date: "",
    status: "",
    updated_at: ""
}